### ISSUE TITLE
create a folder for storing models from recipe-search-api

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/database-visuals#29]
and move json files into it

**Comment by khyati0212** [comment]
moved models from recipe-search-api into /recipeSearchAPI/models folder.

**Comment by atherdon** [comment]
+ remove similar files from repository root and close or mention this issue via commit

**Comment by khyati0212** [comment]
Done. I was not able to work on master branch so created a branch. Deleted duplicated JSON files from root folder. Made a pull request. Merged pull request. Closed this issue using commit.
