### ISSUE TITLE
NASA foodlog

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/database-visuals#9]
https://github.com/ChickenKyiv/foodolog
#7

**Comment by atherdon** [comment]
@khyati0212 while i'm not able to help with your code, maybe you'll be able to take a look on Ian`s future project and write some basic structure for this database too: https://github.com/ChickenKyiv/foodolog/tree/master/images ?

**Comment by khyati0212** [comment]
Hi @atherdon ,

Here is the basic structure of the database as I understood. I also took reference of Grocerystar database schema for creating Foodlog schema. 
Please let me know for your feedback and updates regarding this.

https://sqldbm.com/Project/MySQL/Share/7FT8RJCVSIlgGtRXMZEux0GFrngIE8md_DYjF4jNYw0

**Comment by atherdon** [comment]
it's good. maybe i should add some missin items from that Nasa app, but it's good at this point! Closing it.
Big thanks. and i'll back soon to you
